# Generated by Django 4.2.5 on 2023-10-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0002_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='Usado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='Descrip',
            field=models.TextField(max_length=500),
        ),
    ]
