# Generated by Django 4.2.5 on 2023-10-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0003_articulo_usado_alter_articulo_descrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ItemsPic'),
        ),
    ]
