# Generated by Django 4.2.5 on 2023-10-11 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0004_articulo_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='imagen',
        ),
        migrations.CreateModel(
            name='CargarImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='ItemsPic')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppUser.articulo')),
            ],
        ),
    ]
