# Generated by Django 4.2.5 on 2023-10-12 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0005_remove_articulo_imagen_cargarimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ItemsPic'),
        ),
    ]
