# Generated by Django 4.2.5 on 2023-10-12 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0007_rename_imagen_articulo_imagen_articulo_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CargarImg',
        ),
    ]
